name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'
            
      - name: Instalar as dependencias do Python
        uses: py-actions/py-dependency-install@v2
        with:
          path: "testes/requirements.txt"
    
      - name: Iniciar container
        run: cd testes && docker-compose up -d --build

      - name: Esperar pela disponibilidade do MySQL
        run: |
          echo 'pausing: waiting for mysql to come available'
          ./wait-for-mysql.sh
          echo 'un-pausing: mysql is now available'

      - name: Executar testes
        run: cd testes && robot test_login.robot

      - name: Parar container
        if: always()
        run: cd testes && docker-compose down
