name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'
            
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "testes/requirements.txt"
    
      - name: start container
        run: cd testes && docker-compose up -d --build

      - name: run tests
        run: cd testes && robot test_login.robot

      - name: Stop container
        if: always()
        run: cd testes && docker-compose down
